#!/bin/sh

#脚本格式: 1、 ./cgserver start/stop  zone1  表示(启动/关闭)zone1服的全部进
#	   2、 ./cgserver start/stop  zone1_log 表示(启动/关闭)zone1 Log进程 (其他进程类似)

#不要直接kill -9 关闭进程，特别是线上的时候，等待程序自行完成任务后关闭
	  

ARG=$1
zoneReg="^zone[0-9]*[1-9][0-9]*$"
#zonePart="^zone[0-9]*[1-9][0-9]*_[a-z]+[0-9]*[1-9][0-9]*$"
zonePart="^zone[0-9]*[1-9][0-9]*_[a-z]*$"
config="config"

#hostname=`hostname`
hostname="adamluo"

start() {
	b=`ps fx | grep $1 | grep -v grep | grep -v cgServer | awk '{print $1}'`
	if [[ x"$b" != x ]]; then
		echo "$1 application process already exist pid:$b"
		return 
	fi
	zoneHead=`echo $1 | cut -d \_ -f 1`
	zonePart=`echo $1 | cut -d \_ -f 2`


	mkdir -p $zoneHead
	cp serverd $zoneHead/$1

	echo "starting $1 ...."

	echo $zonePart|sed 's/\b[a-z]/\u&/g' > tmp
	a=`cat tmp`

	if [[ $a = "Chardb" ]]; then
		a="CharDB"
	fi

	cd $zoneHead
	if [ ! -d "data" ]; then
		echo "hahah"
		cp -r ../data data
	fi
	if [ ! -d "MonsterAI" ]; then
		echo "AI"
		cp -r ../MonsterAI MonsterAI
	fi
	nohup ./$1 "$HOME/GameConfig/$hostname/$zoneHead/$a.lua" >/dev/null 2>&1 &
	cd ..

	echo "start $1 done..."
	echo -e ""
	rm tmp
}

stop (){
	b=`ps fx | grep $1 | grep -v grep | grep -v cgServer | awk '{print $1}'`
	if [[ x"$b" = x ]]; then
		echo "cannt find $1 application process"
	fi
	echo "stoping $1 ...."
	kill $b
	echo  "stop $1 done..."
	echo -e ""
}


start_handle() {

	if [[ $1 =~ $zoneReg ]]; then
		start $1"_"chardb
		start $1"_"log
		start $1"_"gate
		start $1"_"center
		start $1"_"logic
	fi

	if [[ $1 =~ $zonePart ]]; then
		start $1
	fi

	if [[ $1 == $config ]]; then
		echo $1
	fi
}

stop_handle() {
	if [[ $1 =~ $zoneReg ]]; then
		stop $1"_"logic
		stop $1"_"log
		stop $1"_"gate
		stop $1"_"center
		stop $1"_"chardb
	fi

	if [[ $1 =~ $zonePart ]]; then
		stop $1
	fi

	if [[ $1 == $config ]]; then
		echo $1
	fi
}

case "$1" in
    start)
        start_handle $2
        ;;
    stop)
        stop_handle  $2
        ;;
    *)
        echo "Please use start, stop as first argument"
        ;;
esac
