#!/bin/sh

#脚本格式: 1、 ./cgserver start/stop  zone1  表示(启动/关闭)zone1服的全部进
#	   2、 ./cgserver start/stop  zone1_log 表示(启动/关闭)zone1 Log进程 (其他进程类似)

#不要直接kill -9 关闭进程，特别是线上的时候，等待程序自行完成任务后关闭
	  

zoneReg="^zone[0-9]*[1-9][0-9]*$"
#zonePart="^zone[0-9]*[1-9][0-9]*_[a-z]+[0-9]*[1-9][0-9]*$"
zonePart="^zone[0-9]*[1-9][0-9]*_[a-z]*$"
config="config"
agent="agent"
hostname=`hostname`
shellDir=$HOME/product/server

start() {
	echo $1
	b=`ps fx | grep $1 | grep -v grep | grep -v cgServer | awk '{print $1}'`
	if [[ x"$b" != x ]]; then
		echo "$1 application process already exist pid:$b"
		return 
	fi
	zoneHead=`echo $1 | cut -d \_ -f 1`
	zonePart=`echo $1 | cut -d \_ -f 2`

	zoneDir=$shellDir/$zoneHead
	echo $zoneDir


	mkdir -p $zoneDir
	cp serverd $zoneDir/$1

	echo "starting $1 ...."

	echo $zonePart|sed 's/\b[a-z]/\u&/g' > tmp
	a=`cat tmp`

	if [[ $a = "Chardb" ]]; then
		a="CharDB"
	fi

	cd $zoneDir
	echo `pwd`
	if [ ! -d "data" ]; then
		cp -r $shellDir/data data
	fi
	if [ ! -d "MonsterAI" ]; then
		cp -r ../MonsterAI MonsterAI
	fi
	#nohup ./$1 "$HOME/GameConfig/$hostname/$zoneHead/$a.lua" >/dev/null 2>&1 &
	nohup ./$1 "$HOME/GameConfig/$hostname/$zoneHead/$a.lua" > $1.log 2>&1 &
	cd $shellDir

	echo "start $1 done..."
	echo -e ""
}

stop (){
	b=`ps fx | grep $1 | grep -v grep | grep -v cgServer | awk '{print $1}'`
	if [[ x"$b" = x ]]; then
		echo "cannt find $1 application process"
		return 
	fi
	echo "stoping $1  pid:$b...."
	kill $b
	echo  "stop $1 done..."
	echo -e ""
}

start_agent(){
	b=`ps fx | grep gameAgent | grep -v grep | grep -v cgServer | awk '{print $1}'`
	if [[ x"$b" != x ]]; then
		echo "gameAgent application process already exist pid:$b"
		return 
	fi
	cd $shellDir/agent
	nohup ./gameAgent > agent.log 2>&1 & 
	cd $shellDir
}


start_handle() {

	if [[ $1 =~ $zoneReg ]]; then
		start $1"_"chardb
		start $1"_"log
		start $1"_"gate
		start $1"_"center
		start $1"_"logic1
		start $1"_"logic2
	fi

	if [[ $1 =~ $zonePart ]]; then
		start $1
	fi

	if [[ $1 == $config ]]; then
		echo $1
	fi
	if [[ $1 == $agent ]]; then
		start_agent 
	fi
}

stop_handle() {
	if [[ $1 =~ $zoneReg ]]; then
		stop $1"_"logic1
		stop $1"_"logic2
		stop $1"_"log
		stop $1"_"gate
		stop $1"_"center
		stop $1"_"chardb
	fi

	if [[ $1 =~ $zonePart ]]; then
		stop $1
	fi

	if [[ $1 == $config ]]; then
		echo $1
	fi

	if [[ $1 == $agent ]]; then
		stop gameAgent
	fi
}

case "$1" in
    start)
        start_handle $2
        ;;
    stop)
        stop_handle  $2
        ;;
    *)
        echo "Please use start, stop as first argument"
        ;;
esac
