#!/bin/sh
git config --global credential.helper store

cp bash_profile ~/.bash_profile
cp vimrc ~/.vimrc

mkdir ~/.vim
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

cp -r .vim/ ~/

