#!/bin/sh

DATABASE="cgzone"
SQLNAME="../../gameTable/zone"

ZONE=$1
if [[ "x$ZONE" = "x" ]]; then
    echo "create cgzoneDB err, pls enter zone num like ./create_zoneDB 1"
    return
fi


echo "create cgzone${ZONE}..."
mysql -f -u cgyx -pcgyx -e "create database if not exists ${DATABASE}${ZONE} character set 'utf8';"
mysql -f -u cgyx -pcgyx -B  ${DATABASE}${ZONE} < ${SQLNAME}.sql
echo "create cgzone${ZONE} done..."

