#!/bin/sh

DATABASE="gameAccount"
SQLNAME="../../gameTable/account"

mysql -f -u cgyx -pcgyx -e "create database if not exists ${DATABASE} character set 'utf8';"
mysql -f -u cgyx -pcgyx -B  ${DATABASE} < ${SQLNAME}.sql
